/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import data.PedidoData;
import data.ProdutoData;
import data.UsuarioData;
import data.VendasData;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Pedido;
import model.Produto;
import model.Vendas;

/**
 *
 * @author mauri
 */
public class JIFVendas extends javax.swing.JInternalFrame {

    private Vector<Produto> listaDeProdutos;
    private Vector<Pedido> listaDePedidos;
    private ArrayList<Vendas> listaDeVendas;
    private ArrayList<Vendas> listaVendidos;

    private Pedido objPedido;
    private Produto objProduto;
    private Vendas objVendas;
    private VendasData DAOVendas;
    private ProdutoData DAOProduto;
    private PedidoData DAOPedido;
    private int acao;

    /**
     * Creates new form JIFVendas
     */
    public JIFVendas() {

        try {
            initComponents();
            desabilitaCampos();
            objVendas = new Vendas();
            objPedido = new Pedido();
            objProduto = new Produto();

            DAOPedido = new PedidoData();
            DAOProduto = new ProdutoData();
            DAOVendas = new VendasData();

            listaDeVendas = new ArrayList<>();

            //jcPedidos.setModel(new DefaultComboBoxModel(listaDePedidos));
            listaDeProdutos = DAOProduto.pesquisarProdutos();
            DefaultComboBoxModel cbModelProduto = (DefaultComboBoxModel) jcProdutos.getModel();

            for (Produto prod : listaDeProdutos) {
                cbModelProduto.addElement(prod.getNomeProd());
            }

            listaDePedidos = DAOPedido.preencheComboBox(0);
            DefaultComboBoxModel cbModelPed = (DefaultComboBoxModel) jcPedidos.getModel();

            for (Pedido ped : listaDePedidos) {
                cbModelPed.addElement(ped.getIdPedido());
            }

            listaVendidos = new ArrayList<>();
            listaVendidos = DAOVendas.pesquisar("");

            DefaultTableModel mp = (DefaultTableModel) jtVendasPesq.getModel();
            mp.setNumRows(0);

            for (Vendas v : listaVendidos) {

                mp.addRow(new String[]{"" + v.getPedido().getIdPedido(), "" + v.getProduto().getIdProduto(),
                    "" + v.getQtdProduto(), "" + v.getValorTotal()});
            }

            //  jcPedidos.setModel(new DefaultComboBoxModel(listaDePedidos));
        } catch (Exception erro) {
            System.out.println(erro.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        qtdVenda = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        valorUni = new javax.swing.JTextField();
        jcPedidos = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jcProdutos = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        btnAdicionar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtVendas = new javax.swing.JTable();
        btnRemoverPedido = new javax.swing.JButton();
        btnSalvarPedidos = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        valorTotal = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtVendasPesq = new javax.swing.JTable();
        pesqVendas = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastrar Venda"));

        qtdVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtdVendaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Quantidade Uni.");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Valor Uni.");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Núm. Pedido");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Produto");

        btnAdicionar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAdicionar.setText("Adicionar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jtVendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Núm. pedido", "Id Produto", "Quantidade", "Valor Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtVendas);

        btnRemoverPedido.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRemoverPedido.setText("Remover");
        btnRemoverPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverPedidoActionPerformed(evt);
            }
        });

        btnSalvarPedidos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSalvarPedidos.setText("Salvar Pedidos");
        btnSalvarPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarPedidosActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Valor Total");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(btnSalvarPedidos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnRemoverPedido))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jcProdutos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcPedidos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(valorUni)
                            .addComponent(qtdVenda, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                            .addComponent(valorTotal))))
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnAdicionar)
                .addGap(53, 53, 53)
                .addComponent(btnCancelar)
                .addGap(106, 106, 106))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qtdVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(valorUni, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(valorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRemoverPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalvarPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Vendas");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisar Produtos Vendidos"));

        jtVendasPesq.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nº Pedido", "Id Produto", "Quantidade", "Valor Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtVendasPesq.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtVendasPesqMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtVendasPesq);

        pesqVendas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pesqVendasKeyReleased(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Pesquisa");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pesqVendas)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pesqVendas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(316, 316, 316))
        );

        btnEditar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnExcluir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(338, 338, 338))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(13, 13, 13))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                            .addComponent(btnExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void qtdVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtdVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qtdVendaActionPerformed

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        // TODO add your handling code here:
        try {

            float valorTot, valorU;
            int qtd;
            qtd = Integer.parseInt(qtdVenda.getText());
            valorU = Float.parseFloat(valorUni.getText());
            valorTot = qtd * valorU;
            objVendas.setValorTotal(valorTot);

            DefaultTableModel mp = (DefaultTableModel) jtVendas.getModel();
            mp.addRow(new String[]{"" + jcPedidos.getSelectedItem(), "" + listaDeProdutos.get(jcProdutos.getSelectedIndex()).getIdProduto(),
                "" + qtdVenda.getText(), "" + objVendas.getValorTotal()});

        } catch (Exception e) {
            System.out.println(e.getMessage());
        }

    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnSalvarPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarPedidosActionPerformed
        // TODO add your handling code here:
        try {
            if (preencherObjeto()) {
                if (DAOVendas.incluir(listaDeVendas)) {
                    JOptionPane.showMessageDialog(this, "Salvo com sucesso!", "Meu sistemas", JOptionPane.INFORMATION_MESSAGE);
                    btnCancelarActionPerformed(evt);
                } else {
                    JOptionPane.showMessageDialog(this, "Não salvou!!");
                }

            }

        } catch (Exception ex) {
            System.out.println(ex.getMessage());
            Logger.getLogger(JIFProduto.class.getName()).log(Level.ALL.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnSalvarPedidosActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void jtVendasPesqMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtVendasPesqMouseClicked
        // TODO add your handling code here:

        try {
            valorUni.setText("");
            listaDePedidos = DAOPedido.preencheComboBox(1);
            DefaultComboBoxModel cbModelPed = (DefaultComboBoxModel) jcPedidos.getModel();
            
            for (Pedido ped : listaDePedidos) {
                cbModelPed.addElement(ped.getIdPedido());
            }

            String nomeProduto = "";

            int linhaSelecionada = jtVendasPesq.getSelectedRow();
            for (Produto produto : listaDeProdutos) {
                if (produto.getIdProduto() == listaVendidos.get(linhaSelecionada).getProduto().getIdProduto()) {
                    nomeProduto = produto.getNomeProd();
                }
            }

            if (linhaSelecionada > -1) {

                qtdVenda.setText("" + listaVendidos.get(linhaSelecionada).getQtdProduto());
                valorTotal.setText("" + listaVendidos.get(linhaSelecionada).getValorTotal());
                jcPedidos.setSelectedItem(listaVendidos.get(linhaSelecionada).getPedido().getIdPedido());
                jcProdutos.setSelectedItem(nomeProduto);

                jcPedidos.setEnabled(false);
                jcProdutos.setEnabled(false);
                btnAdicionar.setEnabled(false);
                btnRemoverPedido.setEnabled(false);
                btnSalvarPedidos.setEnabled(false);
                btnEditar.setEnabled(true);
                btnExcluir.setEnabled(true);
                btnCancelar.setEnabled(true);

            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
            // JOptionPane.showMessageDialog(this, "Erro:" + e.getMessage(), "Erro ao pesquisar", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jtVendasPesqMouseClicked

    private void pesqVendasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pesqVendasKeyReleased
        // TODO add your handling code here:

        try {
            DefaultTableModel mp = (DefaultTableModel) jtVendasPesq.getModel();
            mp.setNumRows(0);

            if (pesqVendas.getText().length() > 0) {
                listaVendidos = DAOVendas.pesquisar(pesqVendas.getText());
                for (Vendas v : listaVendidos) {
                    mp.addRow(new String[]{"" + v.getPedido().getIdPedido(), "" + v.getProduto().getIdProduto(),
                        "" + v.getQtdProduto(), "" + v.getValorTotal()});
                }
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(this, "Erro:" + e.getMessage(), "Erro ao pesquisar", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_pesqVendasKeyReleased

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        acao = 2;
        try {

            if (preencherObjeto()) {
                if (DAOVendas.editar(objVendas)) {
                    JOptionPane.showMessageDialog(this, "Atualizado com sucesso!", "Meu sistemas", JOptionPane.INFORMATION_MESSAGE);
                    btnCancelarActionPerformed(evt);

                } else {
                    JOptionPane.showMessageDialog(this, "Não atualizou!!");
                }
            }

        } catch (Exception ex) {
            System.out.println(ex.getMessage());
            Logger.getLogger(JIFFornecedor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        try {
            if (DAOVendas.excluir(Integer.parseInt("" + objVendas.getPedido().getIdPedido()), Integer.parseInt("" + objVendas.getProduto().getIdProduto()))) {
                JOptionPane.showMessageDialog(this, "Excluído com sucesso!");
                qtdVenda.setText("");
                valorUni.setText("");
                valorTotal.setText("");
                jcPedidos.setSelectedIndex(0);
                jcProdutos.setSelectedIndex(0);
                btnEditar.setEnabled(false);
                btnAdicionar.setEnabled(true);
                btnExcluir.setEnabled(false);
                btnRemoverPedido.setEnabled(true);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro:" + e.getMessage(), "Erro ao pesquisar", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnRemoverPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverPedidoActionPerformed
        // TODO add your handling code here:
        try {
            int linhaSelecionada = jtVendas.getSelectedRow();

            if (linhaSelecionada > -1) {
                DefaultTableModel mp = (DefaultTableModel) jtVendas.getModel();
                mp.removeRow(linhaSelecionada);
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnRemoverPedidoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnRemoverPedido;
    private javax.swing.JButton btnSalvarPedidos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<Integer> jcPedidos;
    private javax.swing.JComboBox<Object> jcProdutos;
    private javax.swing.JTable jtVendas;
    private javax.swing.JTable jtVendasPesq;
    private javax.swing.JTextField pesqVendas;
    private javax.swing.JTextField qtdVenda;
    private javax.swing.JTextField valorTotal;
    private javax.swing.JTextField valorUni;
    // End of variables declaration//GEN-END:variables

    private boolean preencherObjeto() {
        try {

            if (acao == 2) {
                float valorTot, valorU;
                int qtd;
                qtd = Integer.parseInt(qtdVenda.getText());
                valorU = Float.parseFloat(valorUni.getText());
                valorTot = qtd * valorU;

                objVendas.setQtdProduto(Integer.parseInt(qtdVenda.getText()));
                objVendas.setValorTotal(valorTot);
                
                Pedido pedidoSelecionado = new Pedido();
                for (Pedido ped : listaDePedidos) {
                    if (ped.getIdPedido() == Integer.parseInt(jcPedidos.getSelectedItem() + "")) {
                        pedidoSelecionado = ped;
                        System.out.println("Entrou!");
                    }
                }
                objVendas.setPedido(pedidoSelecionado);
                objVendas.setProduto((listaDeProdutos.get(jcProdutos.getSelectedIndex())));

            } else {

                for (int i = 0; i < jtVendas.getRowCount(); i++) {
                    Produto prod = new Produto();
                    Pedido ped = new Pedido();
                    ped.setIdPedido(Integer.parseInt(jtVendas.getValueAt(i, 0).toString()));
                    prod.setIdProduto(Integer.parseInt(jtVendas.getValueAt(i, 1).toString()));
                    Vendas venda = new Vendas(Integer.parseInt(jtVendas.getValueAt(i, 2).toString()),
                            Float.parseFloat(jtVendas.getValueAt(i, 3).toString()), prod, ped);
                    listaDeVendas.add(venda);
                }
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        return true;

    }

    private void desabilitaCampos() {
        btnEditar.setEnabled(false);
        btnExcluir.setEnabled(false);
        valorTotal.setEnabled(false);

    }

}
